export type {
  ScopeKind,
  OrgScope,
  ProjectScope,
  EnvironmentScope,
  AccountScope,
  Scope,
  ResolveScope,
  ConfigRepositoryError,
  ConfigResult,
  CursorPosition,
  PageQueryParams,
  PagedResult,
  Setting,
  CreateSettingInput,
  UpdateSettingInput,
  FeatureFlag,
  CreateFeatureFlagInput,
  UpdateFeatureFlagInput,
  SecretMetadata,
  SecretVersion,
  SecretRotationDue,
  ProviderRotationDue,
  CreateSecretMetadataInput,
  SecretPolicyTier,
  SecretPolicyRecord,
  PutSecretPolicyInput,
  SecretPolicyScope,
  SecretSync,
  SecretSyncStatus,
  RecordSecretSyncInput,
  ListSecretSyncsFilter,
  ConfigRepository,
  SecretDek,
  EnvelopeVersionCounts,
  SecretDekRepository,
} from "./types.js";

export { createConfigRepository } from "./repository.js";
export { createSecretDekRepository } from "./dek-repository.js";
